[variables]
    PYTHONUNBUFFERED = "1"

[phases.setup]
    nixPkgs = ["python3", "gcc"] # Agrega gcc si alguna librería necesita compilar

[phases.install]
    cmds = ["python -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt"]

[start]
    cmd = "/opt/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2"