/** Departamentos de Colombia (33 divisiones: 32 departamentos + Bogotá D.C.) */
export const DEPARTAMENTOS_COLOMBIA = [
  'Amazonas',
  'Antioquia',
  'Arauca',
  'Archipiélago de San Andrés, Providencia y Santa Catalina',
  'Atlántico',
  'Bogotá D.C.',
  'Bolívar',
  'Boyacá',
  'Caldas',
  'Caquetá',
  'Casanare',
  'Cauca',
  'Cesar',
  'Chocó',
  'Córdoba',
  'Cundinamarca',
  'Guainía',
  'Guaviare',
  'Huila',
  'La Guajira',
  'Magdalena',
  'Meta',
  'Nariño',
  'Norte de Santander',
  'Putumayo',
  'Quindío',
  'Risaralda',
  'Santander',
  'Sucre',
  'Tolima',
  'Valle del Cauca',
  'Vaupés',
  'Vichada',
] as const

/** Capitales y ciudades principales por departamento */
export const CIUDADES_POR_DEPARTAMENTO: Record<string, string[]> = {
  Amazonas: ['Leticia'],
  Antioquia: ['Medellín', 'Bello', 'Envigado', 'Itagüí', 'Rionegro'],
  Arauca: ['Arauca'],
  'Archipiélago de San Andrés, Providencia y Santa Catalina': ['San Andrés', 'Providencia'],
  Atlántico: ['Barranquilla', 'Soledad', 'Malambo'],
  'Bogotá D.C.': ['Bogotá'],
  Bolívar: ['Cartagena de Indias', 'Magangué', 'Turbaco'],
  Boyacá: ['Tunja', 'Duitama', 'Sogamoso'],
  Caldas: ['Manizales', 'La Dorada'],
  Caquetá: ['Florencia'],
  Casanare: ['Yopal'],
  Cauca: ['Popayán', 'Santander de Quilichao'],
  Cesar: ['Valledupar', 'Aguachica'],
  Chocó: ['Quibdó'],
  Córdoba: ['Montería', 'Sahagún'],
  Cundinamarca: ['Soacha', 'Facatativá', 'Zipaquirá', 'Girardot'],
  Guainía: ['Inírida'],
  Guaviare: ['San José del Guaviare'],
  Huila: ['Neiva', 'Pitalito'],
  'La Guajira': ['Riohacha', 'Maicao'],
  Magdalena: ['Santa Marta', 'Ciénaga'],
  Meta: ['Villavicencio', 'Acacías'],
  Nariño: ['Pasto', 'Tumaco', 'Ipiales'],
  'Norte de Santander': ['Cúcuta', 'Ocaña'],
  Putumayo: ['Mocoa', 'Puerto Asís'],
  Quindío: ['Armenia', 'Calarcá'],
  Risaralda: ['Pereira', 'Dosquebradas'],
  Santander: ['Bucaramanga', 'Floridablanca', 'Piedecuesta'],
  Sucre: ['Sincelejo', 'Corozal'],
  Tolima: ['Ibagué', 'Espinal'],
  'Valle del Cauca': ['Cali', 'Palmira', 'Buenaventura', 'Tuluá'],
  Vaupés: ['Mitú'],
  Vichada: ['Puerto Carreño'],
}

/** Lista plana de ciudades para dropdown (todas las capitales) */
export const CIUDADES_COLOMBIA = Object.values(CIUDADES_POR_DEPARTAMENTO).flat()
