-- =============================================
-- ERP Inventario - Esquema completo para Supabase
-- Compatible con PostgreSQL 15+
-- =============================================

-- Extensión UUID para auth.users
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================
-- TABLAS BASE
-- =============================================

-- Rol de usuario
CREATE TABLE rol (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Usuario (relacionado con auth.users de Supabase)
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    email VARCHAR(255) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100),
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Relación usuario-rol (many-to-many)
CREATE TABLE usuario_rol (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    rol_id BIGINT NOT NULL REFERENCES rol(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(usuario_id, rol_id)
);

-- Cliente
CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) UNIQUE NOT NULL,
    nombre VARCHAR(200) NOT NULL,
    nit VARCHAR(20),
    direccion VARCHAR(255),
    telefono VARCHAR(50),
    email VARCHAR(255),
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Producto
CREATE TABLE producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(200) NOT NULL,
    descripcion TEXT,
    unidad_medida VARCHAR(20) DEFAULT 'UND',
    precio_unitario DECIMAL(15, 2) NOT NULL CHECK (precio_unitario >= 0),
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índice en código de producto
CREATE INDEX idx_producto_codigo ON producto(codigo);

-- Inventario por producto (stock negativo permitido = faltante para pedidos)
CREATE TABLE inventario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL REFERENCES producto(id) ON DELETE CASCADE,
    stock_actual INTEGER NOT NULL DEFAULT 0,
    stock_minimo INTEGER DEFAULT 0 CHECK (stock_minimo >= 0),
    ubicacion VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(producto_id)
);

-- Movimiento de inventario (stock_anterior/nuevo pueden ser negativos)
CREATE TABLE movimiento_inventario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL REFERENCES producto(id) ON DELETE CASCADE,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('entrada', 'salida', 'ajuste')),
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    stock_anterior INTEGER NOT NULL,
    stock_nuevo INTEGER NOT NULL,
    motivo VARCHAR(255),
    referencia_tipo VARCHAR(50),
    referencia_id BIGINT,
    usuario_id BIGINT REFERENCES usuario(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Pedido
CREATE TABLE pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_pedido VARCHAR(50) NOT NULL UNIQUE,
    cliente_id BIGINT NOT NULL REFERENCES cliente(id) ON DELETE CASCADE,
    usuario_id BIGINT NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    estado VARCHAR(20) NOT NULL DEFAULT 'borrador' 
        CHECK (estado IN ('borrador', 'confirmado', 'en_proceso', 'empaquetado', 'despachado', 'cancelado')),
    subtotal DECIMAL(15, 2) DEFAULT 0 CHECK (subtotal >= 0),
    total DECIMAL(15, 2) DEFAULT 0 CHECK (total >= 0),
    observaciones TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índice en número de pedido
CREATE INDEX idx_pedido_numero ON pedido(numero_pedido);

-- Detalle de pedido
CREATE TABLE detalle_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL REFERENCES pedido(id) ON DELETE CASCADE,
    producto_id BIGINT NOT NULL REFERENCES producto(id) ON DELETE CASCADE,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_unitario DECIMAL(15, 2) NOT NULL CHECK (precio_unitario >= 0),
    subtotal DECIMAL(15, 2) NOT NULL CHECK (subtotal >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Orden de empaque
CREATE TABLE orden_empaque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL REFERENCES pedido(id) ON DELETE CASCADE,
    numero_orden VARCHAR(50) NOT NULL UNIQUE,
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente' 
        CHECK (estado IN ('pendiente', 'en_proceso', 'cerrada', 'cancelada')),
    usuario_id BIGINT REFERENCES usuario(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Detalle de empaque
CREATE TABLE detalle_empaque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_empaque_id BIGINT NOT NULL REFERENCES orden_empaque(id) ON DELETE CASCADE,
    producto_id BIGINT NOT NULL REFERENCES producto(id) ON DELETE CASCADE,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    cantidad_empacada INTEGER DEFAULT 0 CHECK (cantidad_empacada >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Remisión
CREATE TABLE remision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_remision VARCHAR(50) NOT NULL UNIQUE,
    pedido_id BIGINT REFERENCES pedido(id) ON DELETE SET NULL,
    orden_empaque_id BIGINT REFERENCES orden_empaque(id) ON DELETE SET NULL,
    cliente_id BIGINT NOT NULL REFERENCES cliente(id) ON DELETE CASCADE,
    estado VARCHAR(20) NOT NULL DEFAULT 'borrador' 
        CHECK (estado IN ('borrador', 'emitida', 'entregada', 'cancelada')),
    fecha_emision DATE,
    fecha_entrega DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índice en número de remisión
CREATE INDEX idx_remision_numero ON remision(numero_remision);

-- Detalle de remisión
CREATE TABLE detalle_remision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remision_id BIGINT NOT NULL REFERENCES remision(id) ON DELETE CASCADE,
    producto_id BIGINT NOT NULL REFERENCES producto(id) ON DELETE CASCADE,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================
-- FUNCIONES DE ACTUALIZACIÓN
-- =============================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers para updated_at
CREATE TRIGGER update_rol_updated_at BEFORE UPDATE ON rol FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_usuario_updated_at BEFORE UPDATE ON usuario FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_cliente_updated_at BEFORE UPDATE ON cliente FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_producto_updated_at BEFORE UPDATE ON producto FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_inventario_updated_at BEFORE UPDATE ON inventario FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_pedido_updated_at BEFORE UPDATE ON pedido FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_detalle_pedido_updated_at BEFORE UPDATE ON detalle_pedido FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_orden_empaque_updated_at BEFORE UPDATE ON orden_empaque FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_remision_updated_at BEFORE UPDATE ON remision FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =============================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================

ALTER TABLE rol ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuario_rol ENABLE ROW LEVEL SECURITY;
ALTER TABLE cliente ENABLE ROW LEVEL SECURITY;
ALTER TABLE producto ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventario ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimiento_inventario ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedido ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalle_pedido ENABLE ROW LEVEL SECURITY;
ALTER TABLE orden_empaque ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalle_empaque ENABLE ROW LEVEL SECURITY;
ALTER TABLE remision ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalle_remision ENABLE ROW LEVEL SECURITY;

-- Política: Usuarios autenticados pueden leer
CREATE POLICY "usuarios_autenticados_select_rol" ON rol FOR SELECT TO authenticated USING (true);
CREATE POLICY "usuarios_autenticados_select_usuario" ON usuario FOR SELECT TO authenticated USING (true);
CREATE POLICY "usuarios_autenticados_select_usuario_rol" ON usuario_rol FOR SELECT TO authenticated USING (true);
CREATE POLICY "usuarios_autenticados_select_cliente" ON cliente FOR SELECT TO authenticated USING (true);
CREATE POLICY "usuarios_autenticados_select_producto" ON producto FOR SELECT TO authenticated USING (true);
CREATE POLICY "usuarios_autenticados_select_inventario" ON inventario FOR SELECT TO authenticated USING (true);
CREATE POLICY "usuarios_autenticados_select_movimiento_inventario" ON movimiento_inventario FOR SELECT TO authenticated USING (true);
CREATE POLICY "usuarios_autenticados_select_pedido" ON pedido FOR SELECT TO authenticated USING (true);
CREATE POLICY "usuarios_autenticados_select_detalle_pedido" ON detalle_pedido FOR SELECT TO authenticated USING (true);
CREATE POLICY "usuarios_autenticados_select_orden_empaque" ON orden_empaque FOR SELECT TO authenticated USING (true);
CREATE POLICY "usuarios_autenticados_select_detalle_empaque" ON detalle_empaque FOR SELECT TO authenticated USING (true);
CREATE POLICY "usuarios_autenticados_select_remision" ON remision FOR SELECT TO authenticated USING (true);
CREATE POLICY "usuarios_autenticados_select_detalle_remision" ON detalle_remision FOR SELECT TO authenticated USING (true);

-- Política: Solo admin puede insertar/eliminar (asumiendo rol 'admin' tiene id=1)
-- Usamos una función para verificar si el usuario es admin
CREATE OR REPLACE FUNCTION es_admin(auth_uid UUID)
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM usuario u
        JOIN usuario_rol ur ON u.id = ur.usuario_id
        JOIN rol r ON ur.rol_id = r.id
        WHERE u.auth_user_id = auth_uid AND r.nombre = 'admin'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Políticas de INSERT/DELETE para admin
CREATE POLICY "admin_insert_rol" ON rol FOR INSERT TO authenticated WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "admin_delete_rol" ON rol FOR DELETE TO authenticated USING (es_admin(auth.uid()));

CREATE POLICY "admin_insert_usuario" ON usuario FOR INSERT TO authenticated WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "admin_delete_usuario" ON usuario FOR DELETE TO authenticated USING (es_admin(auth.uid()));

CREATE POLICY "admin_insert_usuario_rol" ON usuario_rol FOR INSERT TO authenticated WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "admin_delete_usuario_rol" ON usuario_rol FOR DELETE TO authenticated USING (es_admin(auth.uid()));

CREATE POLICY "admin_insert_cliente" ON cliente FOR INSERT TO authenticated WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "admin_delete_cliente" ON cliente FOR DELETE TO authenticated USING (es_admin(auth.uid()));

CREATE POLICY "admin_insert_producto" ON producto FOR INSERT TO authenticated WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "admin_delete_producto" ON producto FOR DELETE TO authenticated USING (es_admin(auth.uid()));

CREATE POLICY "admin_insert_inventario" ON inventario FOR INSERT TO authenticated WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "admin_delete_inventario" ON inventario FOR DELETE TO authenticated USING (es_admin(auth.uid()));

CREATE POLICY "admin_insert_movimiento_inventario" ON movimiento_inventario FOR INSERT TO authenticated WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "admin_delete_movimiento_inventario" ON movimiento_inventario FOR DELETE TO authenticated USING (es_admin(auth.uid()));

CREATE POLICY "admin_insert_pedido" ON pedido FOR INSERT TO authenticated WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "admin_delete_pedido" ON pedido FOR DELETE TO authenticated USING (es_admin(auth.uid()));

CREATE POLICY "admin_insert_detalle_pedido" ON detalle_pedido FOR INSERT TO authenticated WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "admin_delete_detalle_pedido" ON detalle_pedido FOR DELETE TO authenticated USING (es_admin(auth.uid()));

CREATE POLICY "admin_insert_orden_empaque" ON orden_empaque FOR INSERT TO authenticated WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "admin_delete_orden_empaque" ON orden_empaque FOR DELETE TO authenticated USING (es_admin(auth.uid()));

CREATE POLICY "admin_insert_detalle_empaque" ON detalle_empaque FOR INSERT TO authenticated WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "admin_delete_detalle_empaque" ON detalle_empaque FOR DELETE TO authenticated USING (es_admin(auth.uid()));

CREATE POLICY "admin_insert_remision" ON remision FOR INSERT TO authenticated WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "admin_delete_remision" ON remision FOR DELETE TO authenticated USING (es_admin(auth.uid()));

CREATE POLICY "admin_insert_detalle_remision" ON detalle_remision FOR INSERT TO authenticated WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "admin_delete_detalle_remision" ON detalle_remision FOR DELETE TO authenticated USING (es_admin(auth.uid()));

-- Política: Usuarios autenticados pueden insertar pedidos (crear sus propios pedidos)
CREATE POLICY "usuario_insert_pedido" ON pedido FOR INSERT TO authenticated 
    WITH CHECK (usuario_id IN (SELECT id FROM usuario WHERE auth_user_id = auth.uid()));

CREATE POLICY "usuario_insert_detalle_pedido" ON detalle_pedido FOR INSERT TO authenticated 
    WITH CHECK (EXISTS (
        SELECT 1 FROM pedido p 
        JOIN usuario u ON p.usuario_id = u.id 
        WHERE p.id = pedido_id AND u.auth_user_id = auth.uid()
    ));

-- Política: Solo el usuario que creó el pedido puede modificarlo
CREATE POLICY "usuario_update_pedido" ON pedido FOR UPDATE TO authenticated 
    USING (usuario_id IN (SELECT id FROM usuario WHERE auth_user_id = auth.uid()))
    WITH CHECK (usuario_id IN (SELECT id FROM usuario WHERE auth_user_id = auth.uid()));

CREATE POLICY "usuario_update_detalle_pedido" ON detalle_pedido FOR UPDATE TO authenticated 
    USING (EXISTS (
        SELECT 1 FROM pedido p 
        JOIN usuario u ON p.usuario_id = u.id 
        WHERE p.id = pedido_id AND u.auth_user_id = auth.uid()
    ));

-- Políticas UPDATE para otras tablas (usuarios autenticados con rol apropiado)
CREATE POLICY "authenticated_update_rol" ON rol FOR UPDATE TO authenticated USING (true) WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "authenticated_update_usuario" ON usuario FOR UPDATE TO authenticated USING (true) WITH CHECK (es_admin(auth.uid()) OR auth_user_id = auth.uid());
CREATE POLICY "authenticated_update_cliente" ON cliente FOR UPDATE TO authenticated USING (true) WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "authenticated_update_producto" ON producto FOR UPDATE TO authenticated USING (true) WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "authenticated_update_inventario" ON inventario FOR UPDATE TO authenticated USING (true) WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "authenticated_update_movimiento_inventario" ON movimiento_inventario FOR UPDATE TO authenticated USING (true) WITH CHECK (es_admin(auth.uid()));
CREATE POLICY "authenticated_update_orden_empaque" ON orden_empaque FOR UPDATE TO authenticated USING (true);
CREATE POLICY "authenticated_update_detalle_empaque" ON detalle_empaque FOR UPDATE TO authenticated USING (true);
CREATE POLICY "authenticated_update_remision" ON remision FOR UPDATE TO authenticated USING (true);
CREATE POLICY "authenticated_update_detalle_remision" ON detalle_remision FOR UPDATE TO authenticated USING (true);

-- =============================================
-- DATOS INICIALES
-- =============================================

INSERT INTO rol (nombre, descripcion) VALUES 
    ('admin', 'Administrador del sistema'),
    ('vendedor', 'Usuario vendedor'),
    ('almacen', 'Usuario de almacén');
