-- Producto: tabla producto_lista_precio (codigo + precio por lista)
-- 5 listas: lista_1, lista_2, lista_3, lista_plus, lista_plus_costa

-- 1. Crear tabla producto_lista_precio
CREATE TABLE producto_lista_precio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL REFERENCES producto(id) ON DELETE CASCADE,
    lista VARCHAR(30) NOT NULL CHECK (lista IN ('lista_1', 'lista_2', 'lista_3', 'lista_plus', 'lista_plus_costa')),
    codigo VARCHAR(50) NOT NULL,
    precio DECIMAL(15, 2) NOT NULL CHECK (precio >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(producto_id, lista),
    UNIQUE(lista, codigo)
);

-- 2. Migrar datos existentes: cada producto tiene una lista, codigo y precio
INSERT INTO producto_lista_precio (producto_id, lista, codigo, precio)
SELECT id, lista, codigo, precio FROM producto;

-- 3. Crear filas para las listas faltantes (placeholder: codigo + sufijo + id para unicidad, precio 0)
INSERT INTO producto_lista_precio (producto_id, lista, codigo, precio)
SELECT p.id, 'lista_1', p.codigo || '-L1-' || p.id, 0 FROM producto p
WHERE NOT EXISTS (SELECT 1 FROM producto_lista_precio plp WHERE plp.producto_id = p.id AND plp.lista = 'lista_1');

INSERT INTO producto_lista_precio (producto_id, lista, codigo, precio)
SELECT p.id, 'lista_2', p.codigo || '-L2-' || p.id, 0 FROM producto p
WHERE NOT EXISTS (SELECT 1 FROM producto_lista_precio plp WHERE plp.producto_id = p.id AND plp.lista = 'lista_2');

INSERT INTO producto_lista_precio (producto_id, lista, codigo, precio)
SELECT p.id, 'lista_3', p.codigo || '-L3-' || p.id, 0 FROM producto p
WHERE NOT EXISTS (SELECT 1 FROM producto_lista_precio plp WHERE plp.producto_id = p.id AND plp.lista = 'lista_3');

INSERT INTO producto_lista_precio (producto_id, lista, codigo, precio)
SELECT p.id, 'lista_plus', p.codigo || '-LP-' || p.id, 0 FROM producto p
WHERE NOT EXISTS (SELECT 1 FROM producto_lista_precio plp WHERE plp.producto_id = p.id AND plp.lista = 'lista_plus');

INSERT INTO producto_lista_precio (producto_id, lista, codigo, precio)
SELECT p.id, 'lista_plus_costa', p.codigo || '-LPC-' || p.id, 0 FROM producto p
WHERE NOT EXISTS (SELECT 1 FROM producto_lista_precio plp WHERE plp.producto_id = p.id AND plp.lista = 'lista_plus_costa');

-- Actualizar productos que tenían lista_1 para crear lista_2,3,plus si faltan (el insert anterior puede haber fallado si ya existían)
-- Los INSERT con WHERE NOT EXISTS deberían manejar productos que ya tenían lista_1. Pero los productos migrados solo tienen 1 fila.
-- Necesitamos agregar las 4 listas que faltan. El primer INSERT puso lista del producto (lista_1, lista_2, etc).
-- Si producto tenía lista_1, ya tiene lista_1. Faltan lista_2, lista_3, lista_plus, lista_plus_costa.
-- Los INSERT anteriores usan NOT EXISTS - pero para lista_2,3,plus,plus_costa ninguno existe aún. Good.

-- 4. Eliminar columnas de producto
ALTER TABLE producto DROP CONSTRAINT IF EXISTS producto_lista_check;
ALTER TABLE producto DROP COLUMN IF EXISTS codigo;
ALTER TABLE producto DROP COLUMN IF EXISTS precio;
ALTER TABLE producto DROP COLUMN IF EXISTS lista;
